### ISSUE TITLE
Migrate Accord Project Stack to Concerto 1.0

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/techdocs#360]
## Description

Accord Project has released an alpha version of Concerto. It includes many breaking changes.

This is an umbrella issue to track the work in migrating the Accord Project stack (contract logic DSL, templating system, templates, tools, etc.) to this new version of Concerto.

## Tasks

`depends on` means the dependency has to be completed before the work can really be done on the corresponding project.

- [ ] Publish Concerto 1.0.0-alpha
- [ ] Update Concerto models and pre-publish
- [ ] Update Markdown Transform (depends on Concerto models)
- [ ] Update Ergo (depends on models)
- [ ] Update Cicero (depends on Ergo)
- [ ] Update Templates Library (depends on Cicero)
- [ ] Update VSCode extension (depends on Cicero)
- [ ] Update Web Components (depends on Cicero & Concerto)
- [ ] Update Documentation

## Strategy

First do everything in a systematic `concerto-1.0` branch on all repos until we at least reach the template library.

## Flags

- This is a very delicate stack-wide change, will require maintainers 
- Documentation _could_ happen in parallel, if parallel workers were available.
